---
deploy:
  tasks:
    - export DEPLOYPATH=/home/sohanthink/public_html 
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp portfolio.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/chown -R sohanthink:sohanthink $DEPLOYPATH
  metadata:
    version: 1